version: '3.7'
services:
    jupyter_lab:
        container_name: jupyter
        image: jupyter/datascience-notebook   
        environment:
            - JUPYTER_TOKEN=hi        
        ports:
            - "8080:8888"
        build: 

# Docker-compose debe ser capaz de hacer build del contenedor original